### ISSUE TITLE
USB-Botbase Crashes

### ISSUE THREAD

**Issue by ghost** [MyShiLingStar/ACNHPokerCore#63]
I think the problem is that usb-botbase has had lots of updates since the last release of ACNHPokerCore. And if the user is on HOS 16 they can't switch back to an old one.

The issue:
When using USB-Botbase 2.3 and up from Koi-3088, ACNHPC reads the memory, presents you with your inventory, and maybe will let you change an item. But in USB mode, When you check the critters tab or villagers tab, you're guaranteed to have ANCHPC crash with no warning and no log.

I do have a cheat file present, but did hold L at game boot to disable it. And I've done that for the WiFi mode (sys-botbase) so I don't think this is user error.

**Comment by ghsty** [comment]
I have the same issue, when I connect with USB the basic functionality works and ACNHPC throws me an unhandled exception, all of the top rows disappear.
Here is the exception:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at ACNHPokerCore.Utilities.GetTurnipPrices(Socket socket, USBBot usb) in D:\a\1\s\ACNHPokerCore\Utilities\Utilities.cs:line 849
   at ACNHPokerCore.Main.UpdateTurnipPrices() in D:\a\1\s\ACNHPokerCore\Main.cs:line 5114
   at ACNHPokerCore.Main.USBConnectionButton_Click(Object sender, EventArgs e) in D:\a\1\s\ACNHPokerCore\Main.cs:line 8331
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.CoreLib.dll
----------------------------------------
ACNHPokerCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/ACNHPokerCore.dll
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41905
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.dll
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Hosting.dll
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Hosting.Abstractions.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.DependencyInjection.Abstractions.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.dll
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Caching.Abstractions.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/Accessibility.dll
----------------------------------------
AutocompleteMenu-ScintillaNET
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/AutocompleteMenu-ScintillaNET.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ComponentModel.TypeConverter.dll
----------------------------------------
ToggleSwitch
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/ToggleSwitch.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Drawing.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/mscorlib.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Memory.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Concurrent.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Resources.Extensions.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.ObjectModel.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.Uri.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.Abstractions.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.DependencyInjection.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.Tracing.dll
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.EnvironmentVariables.dll
----------------------------------------
Microsoft.Extensions.Configuration.CommandLine
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.CommandLine.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Primitives.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.FileProviders.Abstractions.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.FileProviders.Physical.dll
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.FileExtensions.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.Json.dll
----------------------------------------
Microsoft.Extensions.Configuration.UserSecrets
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.UserSecrets.dll
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Configuration.Binder.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Linq.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.IO.FileSystem.Watcher.dll
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.FileSystemGlobbing.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Threading.Overlapped.dll
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Options.dll
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.dll
----------------------------------------
Microsoft.Extensions.Diagnostics
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Diagnostics.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Diagnostics.Abstractions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Diagnostics.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.Configuration.dll
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.Debug.dll
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.EventSource.dll
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.EventLog.dll
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Logging.Console.dll
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Options.ConfigurationExtensions.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/System.Text.Json.dll
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/Microsoft.Extensions.Caching.Memory.dll
----------------------------------------
System.Console
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.EventLog
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.23.41904
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/System.Diagnostics.EventLog.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.NonGeneric.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Configuration.ConfigurationManager.dll
----------------------------------------
libc.hwid
    Assembly Version: 6.0.1.0
    Win32 Version: 6.0.1.0
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/libc.hwid.dll
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Private.Xml.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.11/System.Windows.Extensions.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/System.Management.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/Microsoft.Win32.Registry.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Cryptography.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.WebClient.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Runtime.Numerics.dll
----------------------------------------
LibUsbDotNet.LibUsbDotNet
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.29.55645
    CodeBase: file:///C:/Users/ghost/Downloads/ACNHPokerCore/ACNHPokerCore/LibUsbDotNet.LibUsbDotNet.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Sockets.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.Collections.Immutable.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1123.42427
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.11/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
```
Hopefully this helps.
![image](https://github.com/MyShiLingStar/ACNHPokerCore/assets/90712533/4575705d-f8db-439a-997b-b135897c2061)

**Comment by MyShiLingStar** [comment]
My apologies, the last emulator update changed some of the very old code.
And I was too lazy and hadn't tested USB-botbase.
Supporting sys-botbase, usb-botbase, and also emulator means that there are 3 times the work on debugging...

I have just pushed an update to fix the issue. But there might still be more.
Please download the latest build again.
And do not hesitate to post if you happen to find another problem. 
I will try to fix them as soon as possible.
